language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
install:
  - pip install cython backports.tempfile
  - pip install -e '.[develop]'
script:
  - pytest tests
